version: '3'
services:
 db:
  image: mysql:5.7
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: mydb
   MYSQL_USER: user
   MYSQL_PASSWORD: password
 web:
  environment:
   - IMAGE_TAG
  image: "alexelisei/python-app:${IMAGE_TAG}"
  ports:
  - "6000:5000"

